/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.example.photoshare.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FeedsData implements org.apache.thrift.TBase<FeedsData, FeedsData._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FeedsData");

  private static final org.apache.thrift.protocol.TField FEED_FIELD_DESC = new org.apache.thrift.protocol.TField("feed", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FeedsDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FeedsDataTupleSchemeFactory());
  }

  public List<Feed> feed; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FEED((short)1, "feed");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FEED
          return FEED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FEED, new org.apache.thrift.meta_data.FieldMetaData("feed", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Feed.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FeedsData.class, metaDataMap);
  }

  public FeedsData() {
  }

  public FeedsData(
    List<Feed> feed)
  {
    this();
    this.feed = feed;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FeedsData(FeedsData other) {
    if (other.isSetFeed()) {
      List<Feed> __this__feed = new ArrayList<Feed>();
      for (Feed other_element : other.feed) {
        __this__feed.add(new Feed(other_element));
      }
      this.feed = __this__feed;
    }
  }

  public FeedsData deepCopy() {
    return new FeedsData(this);
  }

  @Override
  public void clear() {
    this.feed = null;
  }

  public int getFeedSize() {
    return (this.feed == null) ? 0 : this.feed.size();
  }

  public java.util.Iterator<Feed> getFeedIterator() {
    return (this.feed == null) ? null : this.feed.iterator();
  }

  public void addToFeed(Feed elem) {
    if (this.feed == null) {
      this.feed = new ArrayList<Feed>();
    }
    this.feed.add(elem);
  }

  public List<Feed> getFeed() {
    return this.feed;
  }

  public FeedsData setFeed(List<Feed> feed) {
    this.feed = feed;
    return this;
  }

  public void unsetFeed() {
    this.feed = null;
  }

  /** Returns true if field feed is set (has been assigned a value) and false otherwise */
  public boolean isSetFeed() {
    return this.feed != null;
  }

  public void setFeedIsSet(boolean value) {
    if (!value) {
      this.feed = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FEED:
      if (value == null) {
        unsetFeed();
      } else {
        setFeed((List<Feed>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FEED:
      return getFeed();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FEED:
      return isSetFeed();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FeedsData)
      return this.equals((FeedsData)that);
    return false;
  }

  public boolean equals(FeedsData that) {
    if (that == null)
      return false;

    boolean this_present_feed = true && this.isSetFeed();
    boolean that_present_feed = true && that.isSetFeed();
    if (this_present_feed || that_present_feed) {
      if (!(this_present_feed && that_present_feed))
        return false;
      if (!this.feed.equals(that.feed))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(FeedsData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    FeedsData typedOther = (FeedsData)other;

    lastComparison = Boolean.valueOf(isSetFeed()).compareTo(typedOther.isSetFeed());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFeed()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.feed, typedOther.feed);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FeedsData(");
    boolean first = true;

    sb.append("feed:");
    if (this.feed == null) {
      sb.append("null");
    } else {
      sb.append(this.feed);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FeedsDataStandardSchemeFactory implements SchemeFactory {
    public FeedsDataStandardScheme getScheme() {
      return new FeedsDataStandardScheme();
    }
  }

  private static class FeedsDataStandardScheme extends StandardScheme<FeedsData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FeedsData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FEED
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.feed = new ArrayList<Feed>(_list16.size);
                for (int _i17 = 0; _i17 < _list16.size; ++_i17)
                {
                  Feed _elem18; // required
                  _elem18 = new Feed();
                  _elem18.read(iprot);
                  struct.feed.add(_elem18);
                }
                iprot.readListEnd();
              }
              struct.setFeedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FeedsData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.feed != null) {
        oprot.writeFieldBegin(FEED_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.feed.size()));
          for (Feed _iter19 : struct.feed)
          {
            _iter19.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FeedsDataTupleSchemeFactory implements SchemeFactory {
    public FeedsDataTupleScheme getScheme() {
      return new FeedsDataTupleScheme();
    }
  }

  private static class FeedsDataTupleScheme extends TupleScheme<FeedsData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FeedsData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFeed()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetFeed()) {
        {
          oprot.writeI32(struct.feed.size());
          for (Feed _iter20 : struct.feed)
          {
            _iter20.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FeedsData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.feed = new ArrayList<Feed>(_list21.size);
          for (int _i22 = 0; _i22 < _list21.size; ++_i22)
          {
            Feed _elem23; // required
            _elem23 = new Feed();
            _elem23.read(iprot);
            struct.feed.add(_elem23);
          }
        }
        struct.setFeedIsSet(true);
      }
    }
  }

}

