/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.example.photoshare.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CommentsData implements org.apache.thrift.TBase<CommentsData, CommentsData._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CommentsData");

  private static final org.apache.thrift.protocol.TField FEED_COMMENTS_FIELD_DESC = new org.apache.thrift.protocol.TField("feed_comments", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CommentsDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CommentsDataTupleSchemeFactory());
  }

  public Map<String,List<Comment>> feed_comments; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FEED_COMMENTS((short)1, "feed_comments");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FEED_COMMENTS
          return FEED_COMMENTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FEED_COMMENTS, new org.apache.thrift.meta_data.FieldMetaData("feed_comments", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Comment.class)))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CommentsData.class, metaDataMap);
  }

  public CommentsData() {
  }

  public CommentsData(
    Map<String,List<Comment>> feed_comments)
  {
    this();
    this.feed_comments = feed_comments;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CommentsData(CommentsData other) {
    if (other.isSetFeed_comments()) {
      Map<String,List<Comment>> __this__feed_comments = new HashMap<String,List<Comment>>();
      for (Map.Entry<String, List<Comment>> other_element : other.feed_comments.entrySet()) {

        String other_element_key = other_element.getKey();
        List<Comment> other_element_value = other_element.getValue();

        String __this__feed_comments_copy_key = other_element_key;

        List<Comment> __this__feed_comments_copy_value = new ArrayList<Comment>();
        for (Comment other_element_value_element : other_element_value) {
          __this__feed_comments_copy_value.add(new Comment(other_element_value_element));
        }

        __this__feed_comments.put(__this__feed_comments_copy_key, __this__feed_comments_copy_value);
      }
      this.feed_comments = __this__feed_comments;
    }
  }

  public CommentsData deepCopy() {
    return new CommentsData(this);
  }

  @Override
  public void clear() {
    this.feed_comments = null;
  }

  public int getFeed_commentsSize() {
    return (this.feed_comments == null) ? 0 : this.feed_comments.size();
  }

  public void putToFeed_comments(String key, List<Comment> val) {
    if (this.feed_comments == null) {
      this.feed_comments = new HashMap<String,List<Comment>>();
    }
    this.feed_comments.put(key, val);
  }

  public Map<String,List<Comment>> getFeed_comments() {
    return this.feed_comments;
  }

  public CommentsData setFeed_comments(Map<String,List<Comment>> feed_comments) {
    this.feed_comments = feed_comments;
    return this;
  }

  public void unsetFeed_comments() {
    this.feed_comments = null;
  }

  /** Returns true if field feed_comments is set (has been assigned a value) and false otherwise */
  public boolean isSetFeed_comments() {
    return this.feed_comments != null;
  }

  public void setFeed_commentsIsSet(boolean value) {
    if (!value) {
      this.feed_comments = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FEED_COMMENTS:
      if (value == null) {
        unsetFeed_comments();
      } else {
        setFeed_comments((Map<String,List<Comment>>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FEED_COMMENTS:
      return getFeed_comments();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FEED_COMMENTS:
      return isSetFeed_comments();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CommentsData)
      return this.equals((CommentsData)that);
    return false;
  }

  public boolean equals(CommentsData that) {
    if (that == null)
      return false;

    boolean this_present_feed_comments = true && this.isSetFeed_comments();
    boolean that_present_feed_comments = true && that.isSetFeed_comments();
    if (this_present_feed_comments || that_present_feed_comments) {
      if (!(this_present_feed_comments && that_present_feed_comments))
        return false;
      if (!this.feed_comments.equals(that.feed_comments))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(CommentsData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    CommentsData typedOther = (CommentsData)other;

    lastComparison = Boolean.valueOf(isSetFeed_comments()).compareTo(typedOther.isSetFeed_comments());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFeed_comments()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.feed_comments, typedOther.feed_comments);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CommentsData(");
    boolean first = true;

    sb.append("feed_comments:");
    if (this.feed_comments == null) {
      sb.append("null");
    } else {
      sb.append(this.feed_comments);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CommentsDataStandardSchemeFactory implements SchemeFactory {
    public CommentsDataStandardScheme getScheme() {
      return new CommentsDataStandardScheme();
    }
  }

  private static class CommentsDataStandardScheme extends StandardScheme<CommentsData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CommentsData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FEED_COMMENTS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map24 = iprot.readMapBegin();
                struct.feed_comments = new HashMap<String,List<Comment>>(2*_map24.size);
                for (int _i25 = 0; _i25 < _map24.size; ++_i25)
                {
                  String _key26; // required
                  List<Comment> _val27; // required
                  _key26 = iprot.readString();
                  {
                    org.apache.thrift.protocol.TList _list28 = iprot.readListBegin();
                    _val27 = new ArrayList<Comment>(_list28.size);
                    for (int _i29 = 0; _i29 < _list28.size; ++_i29)
                    {
                      Comment _elem30; // required
                      _elem30 = new Comment();
                      _elem30.read(iprot);
                      _val27.add(_elem30);
                    }
                    iprot.readListEnd();
                  }
                  struct.feed_comments.put(_key26, _val27);
                }
                iprot.readMapEnd();
              }
              struct.setFeed_commentsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CommentsData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.feed_comments != null) {
        oprot.writeFieldBegin(FEED_COMMENTS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.LIST, struct.feed_comments.size()));
          for (Map.Entry<String, List<Comment>> _iter31 : struct.feed_comments.entrySet())
          {
            oprot.writeString(_iter31.getKey());
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, _iter31.getValue().size()));
              for (Comment _iter32 : _iter31.getValue())
              {
                _iter32.write(oprot);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CommentsDataTupleSchemeFactory implements SchemeFactory {
    public CommentsDataTupleScheme getScheme() {
      return new CommentsDataTupleScheme();
    }
  }

  private static class CommentsDataTupleScheme extends TupleScheme<CommentsData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CommentsData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFeed_comments()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetFeed_comments()) {
        {
          oprot.writeI32(struct.feed_comments.size());
          for (Map.Entry<String, List<Comment>> _iter33 : struct.feed_comments.entrySet())
          {
            oprot.writeString(_iter33.getKey());
            {
              oprot.writeI32(_iter33.getValue().size());
              for (Comment _iter34 : _iter33.getValue())
              {
                _iter34.write(oprot);
              }
            }
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CommentsData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map35 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.feed_comments = new HashMap<String,List<Comment>>(2*_map35.size);
          for (int _i36 = 0; _i36 < _map35.size; ++_i36)
          {
            String _key37; // required
            List<Comment> _val38; // required
            _key37 = iprot.readString();
            {
              org.apache.thrift.protocol.TList _list39 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
              _val38 = new ArrayList<Comment>(_list39.size);
              for (int _i40 = 0; _i40 < _list39.size; ++_i40)
              {
                Comment _elem41; // required
                _elem41 = new Comment();
                _elem41.read(iprot);
                _val38.add(_elem41);
              }
            }
            struct.feed_comments.put(_key37, _val38);
          }
        }
        struct.setFeed_commentsIsSet(true);
      }
    }
  }

}

